modLoader = "javafml"
loaderVersion = "[${forge_version},)"
issueTrackerURL = "https://github.com/Layers-of-Railways/CreateNumismatics/issues"
license = "LGPL"

[[mods]]
modId = "numismatics"
version = "${version}"
displayName = "Create: Numismatics"
authors = "IThundxr, Violet, Pink, Slimeist, Razziel"
description = '''
A visually-pleasing and redstone-integrated Create-styled currency mod
'''
logoFile = "icon.png"

[[dependencies.numismatics]]
modId = "forge"
mandatory = true
versionRange = "[${forge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.numismatics]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version}"
ordering = "NONE"
side = "BOTH"

[[dependencies.numismatics]]
modId="create"
mandatory=true
versionRange="${create_forge_version}"
ordering="NONE"
side="BOTH"